### ISSUE TITLE
Non-Hello World samples not working

### ISSUE THREAD

**Issue by csinkers** [davidwengier/SourceGeneratorPlayground#10]
Just tried this out, and all the samples other than Hello World are showing compiler errors, sounds like a reference to the NuGet package Microsoft.CodeAnalysis.CSharp is needed.

e.g. for `Auto Notify` the Output window shows:
```Error(s) compiling generator:

Generator.cs(7,30): error CS0234: The type or namespace name 'CSharp' does not exist in the namespace 'Microsoft.CodeAnalysis' (are you missing an assembly reference?)
Generator.cs(8,30): error CS0234: The type or namespace name 'CSharp' does not exist in the namespace 'Microsoft.CodeAnalysis' (are you missing an assembly reference?)
Generator.cs(170,25): error CS0246: The type or namespace name 'FieldDeclarationSyntax' could not be found (are you missing a using directive or an assembly reference?)
Generator.cs(48,13): error CS0246: The type or namespace name 'CSharpParseOptions' could not be found (are you missing a using directive or an assembly reference?)
Generator.cs(48,66): error CS0246: The type or namespace name 'CSharpCompilation' could not be found (are you missing a using directive or an assembly reference?)
Generator.cs(48,111): error CS0246: The type or namespace name 'CSharpParseOptions' could not be found (are you missing a using directive or an assembly reference?)
Generator.cs(49,74): error CS0103: The name 'CSharpSyntaxTree' does not exist in the current context
Generator.cs(57,22): error CS0246: The type or namespace name 'FieldDeclarationSyntax' could not be found (are you missing a using directive or an assembly reference?)
Generator.cs(60,26): error CS0246: The type or namespace name 'VariableDeclaratorSyntax' could not be found (are you missing a using directive or an assembly reference?)
Generator.cs(170,85): error CS0246: The type or namespace name 'FieldDeclarationSyntax' could not be found (are you missing a using directive or an assembly reference?)
Generator.cs(178,35): error CS0246: The type or namespace name 'FieldDeclarationSyntax' could not be found (are you missing a using directive or an assembly reference?)
```

Same errors seen in firefox and chrome.

**Comment by davidwengier** [comment]
Thanks for the report! Might have to revert #9 and see if that fixes it, though nothing jumps out at me as to what in there would have broken it.

**Comment by davidwengier** [comment]
Confirmed reverting fixes the issue :(

**Comment by davidwengier** [comment]
Thanks, I've reverted the code, things should be working again!

**Comment by csinkers** [comment]
Thanks for looking into it, can confirm the other samples are working now.
